replicaCount: 2

image:
  repository: <aws_account_id>.dkr.ecr.us-west-2.amazonaws.com/tours-travels-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

